### ISSUE TITLE
OSX Wallet crashes upon opening

### ISSUE THREAD

**Issue by ekkis** [BITC2/bitcoin2#2]
the OSX wallet crashes upon opening

every time.  just open it.  it crashes straight away

I just downloaded it.  couldn't say the version # since the app won't come up

OSX 10.14.5 (Mojave).  MacBook Pro

happy to provide a log file is someone will tell me where it's stored

**Comment by Bitc2org** [comment]
Thank you for the report. It has indeed not been tested on all the different Mac versions, in this case Mojave and we'll need to look into it. For the time being the web wallet will be the back up option.

**Comment by ekkis** [comment]
no worries.  glad to have the project.  I'll let you close at will

**Comment by Bitc2org** [comment]
This issue is caused by Mac OS Sandboxing. While waiting for a fix, there is a work-around. When you launch it on Mojave, You'll briefly see a prompt about allowing incoming connections, and if that isn't handled quickly, the app will Crash on High Sierra and Mojave. So only Mac OS programmers typically would know the work-around.

**Comment by Bitc2org** [comment]
Updating the QT dependency should fix this, which was done for the v.2.2 wallet. If you have any issues with the about to be released v.2.2 wallet, let us know please.
